package com.whut.mine.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.whut.mine.entity.CheckTableFirstIndex;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CheckTableFirstIndex_T".
*/
public class CheckTableFirstIndexDao extends AbstractDao<CheckTableFirstIndex, Long> {

    public static final String TABLENAME = "CheckTableFirstIndex_T";

    /**
     * Properties of entity CheckTableFirstIndex.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property FirstIndexID = new Property(0, Long.class, "firstIndexID", true, "FirstIndexID");
        public final static Property CheckTableID = new Property(1, int.class, "checkTableID", false, "CheckTableID");
        public final static Property SerialNum = new Property(2, int.class, "serialNum", false, "SerialNum");
        public final static Property FirstIndexName = new Property(3, String.class, "firstIndexName", false, "FirstIndexName");
        public final static Property Deleted = new Property(4, String.class, "deleted", false, "Deleted");
        public final static Property AddTime = new Property(5, String.class, "addTime", false, "AddTime");
        public final static Property DeleteTime = new Property(6, String.class, "deleteTime", false, "DeleteTime");
    }


    public CheckTableFirstIndexDao(DaoConfig config) {
        super(config);
    }
    
    public CheckTableFirstIndexDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CheckTableFirstIndex_T\" (" + //
                "\"FirstIndexID\" INTEGER PRIMARY KEY NOT NULL ," + // 0: firstIndexID
                "\"CheckTableID\" INTEGER NOT NULL ," + // 1: checkTableID
                "\"SerialNum\" INTEGER NOT NULL ," + // 2: serialNum
                "\"FirstIndexName\" TEXT," + // 3: firstIndexName
                "\"Deleted\" TEXT," + // 4: deleted
                "\"AddTime\" TEXT," + // 5: addTime
                "\"DeleteTime\" TEXT);"); // 6: deleteTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CheckTableFirstIndex_T\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CheckTableFirstIndex entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getFirstIndexID());
        stmt.bindLong(2, entity.getCheckTableID());
        stmt.bindLong(3, entity.getSerialNum());
 
        String firstIndexName = entity.getFirstIndexName();
        if (firstIndexName != null) {
            stmt.bindString(4, firstIndexName);
        }
 
        String deleted = entity.getDeleted();
        if (deleted != null) {
            stmt.bindString(5, deleted);
        }
 
        String addTime = entity.getAddTime();
        if (addTime != null) {
            stmt.bindString(6, addTime);
        }
 
        String deleteTime = entity.getDeleteTime();
        if (deleteTime != null) {
            stmt.bindString(7, deleteTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CheckTableFirstIndex entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getFirstIndexID());
        stmt.bindLong(2, entity.getCheckTableID());
        stmt.bindLong(3, entity.getSerialNum());
 
        String firstIndexName = entity.getFirstIndexName();
        if (firstIndexName != null) {
            stmt.bindString(4, firstIndexName);
        }
 
        String deleted = entity.getDeleted();
        if (deleted != null) {
            stmt.bindString(5, deleted);
        }
 
        String addTime = entity.getAddTime();
        if (addTime != null) {
            stmt.bindString(6, addTime);
        }
 
        String deleteTime = entity.getDeleteTime();
        if (deleteTime != null) {
            stmt.bindString(7, deleteTime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public CheckTableFirstIndex readEntity(Cursor cursor, int offset) {
        CheckTableFirstIndex entity = new CheckTableFirstIndex( //
            cursor.getLong(offset + 0), // firstIndexID
            cursor.getInt(offset + 1), // checkTableID
            cursor.getInt(offset + 2), // serialNum
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // firstIndexName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // deleted
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // addTime
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // deleteTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CheckTableFirstIndex entity, int offset) {
        entity.setFirstIndexID(cursor.getLong(offset + 0));
        entity.setCheckTableID(cursor.getInt(offset + 1));
        entity.setSerialNum(cursor.getInt(offset + 2));
        entity.setFirstIndexName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDeleted(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setAddTime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDeleteTime(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CheckTableFirstIndex entity, long rowId) {
        entity.setFirstIndexID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CheckTableFirstIndex entity) {
        if(entity != null) {
            return entity.getFirstIndexID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CheckTableFirstIndex entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
