package com.whut.mine.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.whut.mine.entity.CheckTableFirstIndex;
import com.whut.mine.entity.CheckTableSecondIndex;
import com.whut.mine.entity.Institution;
import com.whut.mine.entity.SafetyCheckTable;
import com.whut.mine.entity.SafetyCheckTableDetail;
import com.whut.mine.entity.SafetyCheckTableInfo;
import com.whut.mine.entity.User;

import com.whut.mine.greendao.CheckTableFirstIndexDao;
import com.whut.mine.greendao.CheckTableSecondIndexDao;
import com.whut.mine.greendao.InstitutionDao;
import com.whut.mine.greendao.SafetyCheckTableDao;
import com.whut.mine.greendao.SafetyCheckTableDetailDao;
import com.whut.mine.greendao.SafetyCheckTableInfoDao;
import com.whut.mine.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig checkTableFirstIndexDaoConfig;
    private final DaoConfig checkTableSecondIndexDaoConfig;
    private final DaoConfig institutionDaoConfig;
    private final DaoConfig safetyCheckTableDaoConfig;
    private final DaoConfig safetyCheckTableDetailDaoConfig;
    private final DaoConfig safetyCheckTableInfoDaoConfig;
    private final DaoConfig userDaoConfig;

    private final CheckTableFirstIndexDao checkTableFirstIndexDao;
    private final CheckTableSecondIndexDao checkTableSecondIndexDao;
    private final InstitutionDao institutionDao;
    private final SafetyCheckTableDao safetyCheckTableDao;
    private final SafetyCheckTableDetailDao safetyCheckTableDetailDao;
    private final SafetyCheckTableInfoDao safetyCheckTableInfoDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        checkTableFirstIndexDaoConfig = daoConfigMap.get(CheckTableFirstIndexDao.class).clone();
        checkTableFirstIndexDaoConfig.initIdentityScope(type);

        checkTableSecondIndexDaoConfig = daoConfigMap.get(CheckTableSecondIndexDao.class).clone();
        checkTableSecondIndexDaoConfig.initIdentityScope(type);

        institutionDaoConfig = daoConfigMap.get(InstitutionDao.class).clone();
        institutionDaoConfig.initIdentityScope(type);

        safetyCheckTableDaoConfig = daoConfigMap.get(SafetyCheckTableDao.class).clone();
        safetyCheckTableDaoConfig.initIdentityScope(type);

        safetyCheckTableDetailDaoConfig = daoConfigMap.get(SafetyCheckTableDetailDao.class).clone();
        safetyCheckTableDetailDaoConfig.initIdentityScope(type);

        safetyCheckTableInfoDaoConfig = daoConfigMap.get(SafetyCheckTableInfoDao.class).clone();
        safetyCheckTableInfoDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        checkTableFirstIndexDao = new CheckTableFirstIndexDao(checkTableFirstIndexDaoConfig, this);
        checkTableSecondIndexDao = new CheckTableSecondIndexDao(checkTableSecondIndexDaoConfig, this);
        institutionDao = new InstitutionDao(institutionDaoConfig, this);
        safetyCheckTableDao = new SafetyCheckTableDao(safetyCheckTableDaoConfig, this);
        safetyCheckTableDetailDao = new SafetyCheckTableDetailDao(safetyCheckTableDetailDaoConfig, this);
        safetyCheckTableInfoDao = new SafetyCheckTableInfoDao(safetyCheckTableInfoDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(CheckTableFirstIndex.class, checkTableFirstIndexDao);
        registerDao(CheckTableSecondIndex.class, checkTableSecondIndexDao);
        registerDao(Institution.class, institutionDao);
        registerDao(SafetyCheckTable.class, safetyCheckTableDao);
        registerDao(SafetyCheckTableDetail.class, safetyCheckTableDetailDao);
        registerDao(SafetyCheckTableInfo.class, safetyCheckTableInfoDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        checkTableFirstIndexDaoConfig.clearIdentityScope();
        checkTableSecondIndexDaoConfig.clearIdentityScope();
        institutionDaoConfig.clearIdentityScope();
        safetyCheckTableDaoConfig.clearIdentityScope();
        safetyCheckTableDetailDaoConfig.clearIdentityScope();
        safetyCheckTableInfoDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public CheckTableFirstIndexDao getCheckTableFirstIndexDao() {
        return checkTableFirstIndexDao;
    }

    public CheckTableSecondIndexDao getCheckTableSecondIndexDao() {
        return checkTableSecondIndexDao;
    }

    public InstitutionDao getInstitutionDao() {
        return institutionDao;
    }

    public SafetyCheckTableDao getSafetyCheckTableDao() {
        return safetyCheckTableDao;
    }

    public SafetyCheckTableDetailDao getSafetyCheckTableDetailDao() {
        return safetyCheckTableDetailDao;
    }

    public SafetyCheckTableInfoDao getSafetyCheckTableInfoDao() {
        return safetyCheckTableInfoDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
